services:
  jenkins:
    container_name: jenkins
    image: docker.io/jenkins/jenkins:lts
    user: "${UID:-1003}:${GID:-1003}"
    ports:
      - 0.0.0.0:${JENKINS_PORT_EXTERNAL:-1080}:${JENKINS_PORT_INTERNAL:-80}
    volumes:
      - ./service/jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--httpPort=${JENKINS_PORT_INTERNAL:-80}"
    restart: always
    networks:
      - jenkins_net
    healthcheck:
      test: curl -fsSL http://localhost:${JENKINS_PORT_INTERNAL:-80}/login || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s


  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "0.0.0.0:${FIREWALL_PORT_EXTERNAL:-80}:${FIREWALL_PORT_INTERNAL:-80}"
    volumes:
      - ./service/nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service/nginx_conf/proxy_params:/etc/nginx/proxy_params:ro
      - ./service/nginx_logs:/var/log/nginx
    depends_on:
      jenkins:
        condition: service_healthy
      agent:
        condition: service_healthy
    restart: always
    networks:
      - jenkins_net
    healthcheck:
      test: curl -fsSL http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  jenkins_net:
    driver: bridge
