events {}

http {
    server {
        listen ${NGINX_LISTEN_PORT};
        server_name ${NGINX_SERVER_NAME};

        access_log /var/log/nginx/jenkins.access.log;
        error_log  /var/log/nginx/jenkins.error.log;

        location = /crumbIssuer/api/json {
            if ($request_method != "GET") {
                return 403;
            }
            proxy_pass http://${JENKINS_UPSTREAM};
            include /etc/nginx/proxy_params;
        }

        # Allow triggering any Jenkins job's buildWithParameters endpoint.
        location ~ ^/job/[^/]+/buildWithParameters$ {
            if ($request_method != "POST") {
                return 403;
            }
            proxy_pass http://${JENKINS_UPSTREAM};
            include /etc/nginx/proxy_params;
        }

        location / {
            allow ${NGINX_ADMIN_IP};  # IP access
            #allow 172.19.0.1;   # Docker host access (only when using default network)
            allow 127.0.0.1;    # Within the container access
            deny all;

            proxy_pass http://${JENKINS_UPSTREAM};
            include /etc/nginx/proxy_params;
        }
        location /healthz {
          return 200 'OK';
          add_header Content-Type text/plain;
        }
    }
}
